# 2021110200

js_var $cors_config_file; # set or override in server or location contexts of nginx configuration to point to configuration file
js_var $cors_is_valid_preflight_request; # set by cors.header_filter to signal detection of a valid pre-flight request

js_import cors from /etc/nginx/njs/http/cors.js;

# JSON configuration pointed by cors_config_file variable should follow next guidelines:
#
#   allowed_origins:	string "omit" | string "mirror" | string "*" | array of strings ; (default: "*")
#   allowed_methods:	string "omit" | string "mirror" | string "*" | array of strings ; (default: [ "OPTIONS", "GET", "POST", "HEAD", "PUT", "DELETE" ])
#   allowed_headers:	string "mirror" | string "*" | array of strings ; (default: "mirror")
#   exposed_headers:	string "omit" | string "*" |  array of strings ; (default: "omit")
#   max_age:		string "omit" | an unsigned non-negative integer (<= 7200) ; (default: 7200)
#   allow_credentials:	string "omit" | a boolean value ; (default: true)
#
# See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
# See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods
# See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
# See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
# See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age
# See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials
