# Please only include ngx_http_proxy_module directives suitable for
#   Context:	http, server, location

#    proxy_set_header Connection ""; # Enable keepalives
    proxy_set_header Accept-Encoding ""; # Optimize encoding
    proxy_set_header X-Real-IP $remote_addr;
#    proxy_set_header X-Forwarded-Port $http_x_forwarded_port;
    proxy_set_header X-Forwarded-Proto $scheme;
